[project]
name = "data-engine"
version = "0.0.1"
description = "Performs multiple tasks related to the data management."
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "pandas>=2.2.3",
    "prophet>=1.1.5",
    "numpy>=2.0",
    "faststream[redis]>=0.5.30",
    "cvxpy>=1.5.3",
    "apscheduler>=3.10.4",
    "schedule>=1.2.2",
    "python-dotenv>=1.0.1",
    "debugpy>=1.8.12",
    "influxdb-client>=1.46.0",
    "pytz>=2024.1",
    "pydantic>=2.10.2",
    "common",
]

[tool.uv.sources]
common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_engine"]
